seniorproj/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('watchlist/', include('watchlist.urls')),
    path('admin/', admin.site.urls),
]

watchlist/urls.py
from django.urls import path

from . import views

app_name = 'watchlist'
urlpatterns = [
    path('<list_name>/movies', views.movie_index, name='movie_index'),
    path('<list_name>/shows', views.show_index, name='show_index'),
    path('<list_name>/actors', views.actor_index, name='actor_index'),

    path('<int:movie_id>/movie-details', views.movie_detail, name='movie_detail'),
    path('<int:show_id>/show-details', views.show_detail, name='show_detail'),
    path('<int:actor_id>/actor-details', views.actor_detail, name='actor_detail'),

    path('<int:movie_id>/movie-cast', views.movie_cast, name='movie_cast'),
    path('<int:show_id>/show-cast', views.show_cast, name='show_cast'),

    path('movie-options/<list_name>/<search_text>', views.new_movie_options, name='new_movie_options'),
    path('show-options/<list_name>/<search_text>', views.new_show_options, name='new_show_options')
]

watchlist/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from decimal import Decimal

class WatchList(models.Model):
    name = models.CharField(max_length=10)
    color = models.CharField(max_length=7, default="#ffffff")

    def __str__(self):
        return self.name

class Movie(models.Model):

    TOWATCH = 'TW'
    WATCHED = 'WD'

    WATCH_STATE_CHOICES = [
        (TOWATCH, 'To watch'),
        (WATCHED, 'Watched')
    ]

    list = models.ForeignKey(WatchList, on_delete = models.CASCADE, null=True, blank=True)
    movie_title = models.CharField(max_length = 200)
    url = models.CharField(max_length = 200, null = True)
    synopsis = models.CharField(max_length = 400, null = True)
    featured_img = models.ImageField(null = True)
    watch_state = models.CharField(
        choices = WATCH_STATE_CHOICES,
        max_length = 2,
        default = TOWATCH
    )
    rating = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        default=0,
        validators=[MinValueValidator(Decimal('0.00'))]
        )

    queued = models.BooleanField(default = False)
    watch_date = models.DateField(null = True, default = None)

    def __str__(self):
        return self.movie_title


class Show(models.Model):
    TOWATCH = 'TW'
    WATCHING = 'WG'
    WATCHED = 'WD'

    WATCH_STATE_CHOICES = [
        (TOWATCH, 'To watch'),
        (WATCHING, 'Watching'),
        (WATCHED, 'Watched')
    ]

    show_title = models.CharField(max_length=200)
    list = models.ForeignKey(WatchList, on_delete=models.CASCADE, null=True, blank=True)
    url = models.CharField(max_length = 200, null = True)
    synopsis = models.CharField(max_length=400, null=True)
    featured_img = models.ImageField(null=True)
    watch_state = models.CharField(
        choices = WATCH_STATE_CHOICES,
        max_length = 2,
        default = TOWATCH
    )
    rating = models.DecimalField(max_digits=3, decimal_places=2, default=0)
    queued = models.BooleanField(default=False)
    start_date = models.DateField(null = True, default = None)
    finish_date = models.DateField(null = True, default = None)

    def __str__(self):
        return self.show_title

class Actor(models.Model):
    name = models.CharField(max_length=200)
    list = models.ForeignKey(
        WatchList,
        on_delete = models.CASCADE,
        null=True, blank=True
    )
    imdb_id = models.IntegerField(
        validators=[MinValueValidator(0)])

    def __str__(self):
        return self.name

class Role(models.Model):
    name = models.CharField(max_length=200)
    actor = models.ForeignKey(
        Actor,
        on_delete = models.CASCADE,
        null=True,
        blank=True
    )
    movie = models.ForeignKey(
        Movie,
        on_delete = models.CASCADE,
        default = None,
        null = True
    )
    show = models.ForeignKey(
        Show,
        on_delete = models.CASCADE,
        default = None,
        null = True
    )
    seen = models.BooleanField(default = False)

    def __str__(self):
        return self.name

watchlist/forms.py
from django import forms


class NewMovieOptionsForm(forms.Form):
    def __init__(self, *args, **kwargs):
        movie_choices = kwargs.pop('movie_choices')
        super(NewMovieOptionsForm, self).__init__(*args, **kwargs)
        self.fields['movie_url'].choices = movie_choices

    movie_url = forms.ChoiceField(
        label='Which one is it?',
        required = False
    )

class UpdateMovieForm(forms.Form):
    new_rating = forms.DecimalField(
        label = 'Rating',
        required = False,
    )
    new_watch_state = forms.ChoiceField(
        label='Seen it?',
        choices = [('TW', 'To watch'), ('WD', 'Watched')],
        required = False
    )
    delete_movie = forms.CharField(
        label='Type "delete" to delete',
        max_length=6,
        required = False
    )
    queued = forms.BooleanField(required=False)


class UpdateShowForm(forms.Form):
    new_rating = forms.DecimalField(
        label = 'Rating',
        required = False,
    )
    new_watch_state = forms.ChoiceField(
        label='Seen it?',
        choices = [('TW', 'To watch'),('WG', 'Watching'), ('WD', 'Watched')],
        required = False
    )
    delete_show = forms.CharField(
        label='Type "delete" to delete',
        max_length=6,
        required = False
    )
    queued = forms.BooleanField(required=False)

watchlist/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from bs4 import BeautifulSoup
import requests

from .models import Movie, WatchList, Show
from .forms import UpdateMovieForm, UpdateShowForm, NewMovieOptionsForm
from datetime import date
from .utils import *


#Index Views

def movie_index(request, list_name):
    watchlst = get_object_or_404(WatchList, name=list_name)
    wl_movies = Movie.objects.filter(list=watchlst)
    ranked_list = wl_movies.filter(watch_state="WD").order_by('-rating')
    chronological_list = wl_movies.filter(watch_state="WD").order_by('watch_date')
    to_watch_queued = wl_movies.filter(watch_state="TW").filter(queued=True)
    to_watch_list = wl_movies.filter(watch_state="TW").filter(queued=False)
    lists = []
    for list in WatchList.objects.all():
        if list.name != list_name:
            lists.append(list)

    context = {'watchlst': watchlst,
                'lists': lists,
                'ranked_list': ranked_list,
                'chronological_list': chronological_list,
                'to_watch_queued': to_watch_queued,
                'to_watch_list': to_watch_list
    }

    return render(request, 'watchlist/movie_index.html', context)

def show_index(request, list_name):
    watchlst = get_object_or_404(WatchList, name=list_name)
    wl_shows = Show.objects.filter(list=watchlst)
    ranked_list = wl_shows.filter(watch_state="WD").order_by('-rating')
    chronological_list = wl_shows.filter(watch_state="WD").order_by('-finish_date')

    to_watch_list = wl_shows.filter(watch_state="TW")
    watching_list_queued = wl_shows.filter(watch_state="WG").filter(queued=True)
    watching_list = wl_shows.filter(watch_state="WG").filter(queued=False)
    to_watch_queued = wl_shows.filter(watch_state="TW").filter(queued=True)
    to_watch_list = wl_shows.filter(watch_state="TW").filter(queued=False)
    lists = []
    for list in WatchList.objects.all():
        if list.name != list_name:
            lists.append(list)

    context = {'watchlst': watchlst,
                'lists': lists,
                'ranked_list': ranked_list,
                'chronological_list': chronological_list,
                'watching_list_queued': watching_list_queued,
                'watching_list': watching_list,
                'to_watch_queued': to_watch_queued,
                'to_watch_list': to_watch_list
    }

    return render(request, 'watchlist/show_index.html', context)

def actor_index(request, list_name):
    watchlst = get_object_or_404(WatchList, name=list_name)

    actor_occurances = []   #accumulate list of actors that are in list more than once
                            #(actor, occurances)
    for actor in Actor.objects.filter(list=watchlst):
        n = len(Role.objects.filter(actor=actor))
        if n > 1:
            actor_occurances.append((actor, n))
        elif n == 0:
            actor.delete()

    actor_occurances.sort(reverse=True, key=lambda tup: tup[1])
    context = { 'watchlst': watchlst, 'actor_occurances': actor_occurances }

    return render(request, 'watchlist/actor-index.html', context)


#Detail Views

def movie_detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    if request.method == 'POST':
        movie = get_object_or_404(Movie, pk=movie_id)

        form = UpdateMovieForm(request.POST)
        if form.is_valid():
            if movie.watch_state != 'WD' and form.cleaned_data['new_watch_state'] == 'WD':
                movie.watch_date = date.today().strftime("%Y-%m-%d")

            movie.watch_state = form.cleaned_data['new_watch_state']
            if form.cleaned_data['new_rating'] != None:
                movie.rating = form.cleaned_data['new_rating']
            movie.queued = form.cleaned_data['queued']
            movie.save()

            if str(form.cleaned_data['delete_movie']) == 'delete':
                movie.delete()

            return HttpResponseRedirect("/watchlist/" + movie.list.name + "/movies")
    else:
        form = UpdateMovieForm(request.POST, movie)

    return render(request, 'watchlist/movie-detail.html', {'movie': movie, 'form': form})

def show_detail(request, show_id):
    show = get_object_or_404(Show, pk=show_id)

    if request.method == 'POST':
        sform = UpdateShowForm(request.POST)
        if sform.is_valid():
            if show.watch_state == 'TW' and sform.cleaned_data['new_watch_state'] == 'WG':
                show.start_date = date.today().strftime("%Y-%m-%d")
            if show.watch_state != 'WD' and sform.cleaned_data['new_watch_state'] == 'WD':
                show.finish_date = date.today()

            show.watch_state = sform.cleaned_data['new_watch_state']
            if sform.cleaned_data['new_rating'] != None:
                show.rating = sform.cleaned_data['new_rating']
            show.queued = sform.cleaned_data['queued']
            show.save()

            if str(sform.cleaned_data['delete_show']) == 'delete':
                show.delete()

            return HttpResponseRedirect("/watchlist/" + show.list.name + "/shows")
    else:
        form = UpdateShowForm(request.POST, show)

    return render(request, 'watchlist/show-detail.html', {'show': show, 'form': form})

def actor_detail(request, actor_id):
    actor = get_object_or_404(Actor, pk=actor_id)
    roles = Role.objects.filter(actor=actor)

    context = { 'actor': actor, 'roles': roles}

    return render(request, 'watchlist/actor-detail.html', context)


#Cast Views

def movie_cast(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    title_roles = Role.objects.filter(movie=movie)
    context = {'title': movie, 'roles': title_roles, "title_type": Movie}

    return render(request, 'watchlist/cast-list.html', context)


def show_cast(request, show_id):
    show = get_object_or_404(Show, pk=show_id)
    title_roles = Role.objects.filter(show=show)
    context = {'title': show, 'roles': title_roles, "title_type": Show}

    return render(request, 'watchlist/cast-list.html', context)



#New Title Views

def new_movie_options(request, list_name, search_text):
    watchlst = get_object_or_404(WatchList, name = list_name)
    choices = find_choices(search_text, "movie")

    if request.method == 'POST':
        form = NewMovieOptionsForm(request.POST, movie_choices = choices)
        if form.is_valid():

            newmov = Movie()
            url = form.cleaned_data['movie_url']
            movie_page = requests.get(url)
            soup = BeautifulSoup(movie_page.content, 'html.parser')

            newmov.movie_title = soup.find('div', class_='title_wrapper').h1.get_text()
            newmov.synopsis = soup.find_all('div', class_='summary_text')[0].get_text()
            newmov.featured_img = soup.find('div', class_='poster').img['src']
            newmov.list = watchlst
            newmov.url = url

            newmov.save()

            add_roles(newmov)

            return HttpResponseRedirect("/watchlist/" + watchlst.name + "/movies")
    else:
        form = NewMovieOptionsForm(movie_choices = choices)

    return render(request, 'watchlist/newmovieoptions.html', {'watchlst': watchlst, 'form': form, 'search_text': search_text})


def new_show_options(request, list_name, search_text):
    watchlst = get_object_or_404(WatchList, name = list_name)
    choices = find_choices(search_text, "show")

    if request.method == 'POST':
        form = NewMovieOptionsForm(request.POST, movie_choices = choices)

        if form.is_valid():
            newshow = Show()
            url = form.cleaned_data['movie_url']
            show_page = requests.get(url)
            soup = BeautifulSoup(show_page.content, 'html.parser')

            newshow.show_title = soup.find('div', class_='title_wrapper').h1.get_text()
            newshow.synopsis = soup.find_all('div', class_='summary_text')[0].get_text()
            newshow.featured_img = soup.find('div', class_='poster').img['src']
            newshow.list = watchlst

            newshow.save()

            return HttpResponseRedirect("/watchlist/" + watchlst.name + "/shows")
    else:
        form = NewMovieOptionsForm(movie_choices = choices)

    return render(request, 'watchlist/newshowoptions.html', {'watchlst': watchlst, 'form': form, 'search_text': search_text})

watchlist/templates/watchlist/actor-detail.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/actor_detail.css' %}">
</head>
<div id="page-content">
    <h1>{{actor.name}}</h1>
    <div id="role-list">
        {% for role in roles %}
          {% if role.movie %}
            <div class="role-container">
                <img class="preview-img" src="{{role.movie.featured_img}}">
                <h2>{{ role.name }}</h2>
                <p>{{ role.movie.movie_title }}</p>
            </div>
          {% endif %}
          {% if role.show != None %}
            <div class="role-container">
                <img class="preview-img" src="{{role.show.featured_img}}">
                <h2>{{ role.name }}</h2>
                <p>{{ role.show.show_title }}</p>
            </div>
          {% endif %}
        {% endfor %}
    </div>
</div>

watchlist/templates/watchlist/actor-index.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/actor_index.css' %}">
</head>
<div class="page-content">
  <div class="header">
    <h1>{{ watchlst }}'s Actors</h1>
  </div>
  <div id="actor-list">
      {% for actor in actor_occurances %}
          <div class="actor-container">
              <h2><a href="{% url 'watchlist:actor_detail' actor.0.id %}">{{ actor.0.name }}</a></h2>
              <p>{{ actor.1 }} appearances</p>
          </div>
      {% endfor %}
  </div>

</div>

watchlist/templates/watchlist/cast-list.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/actor_index.css' %}">
</head>
<div class="page-content">
    <div class="header">
        {% if title_type == Show %}
            <h1>{{ title.show_title }} Cast</h1>
        {% else %}
            <h1>{{ title.movie_title }} Cast</h1>
        {% endif %}
    </div>
    <div id="actor-list">
        {% for role in roles %}
            <div class="actor-container">
                <h2>{{ role.name }}</h2>
                <p><a href="{% url 'watchlist:actor_detail' role.actor.id %}">{{ role.actor }}</a></p>
            </div>
        {% endfor %}

</div>

watchlist/templates/watchlist/detail.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<a href="/watchlist/{{movie.list.name}}">
  <img src="{% static 'images/arrow.svg' %}" alt="back to list" id="back-arrow">
</a>
<div class="page-content">
  <div class="header">
    <h1>{{ movie.movie_title }}</h1>
    {% if movie.watch_state == "WD" %}
      <p>{{ movie.rating }}</p>
    {% endif %}
  </div>
  <div>
  <p class="movie-summary">{{ movie.synopsis }}</p>

  <form action="{% url 'watchlist:detail' movie.id %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="update">
  </form>

</div>

watchlist/templates/watchlist/movie-detail.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<a href="/watchlist/{{movie.list.name}}/movies">
  <img src="{% static 'images/arrow.svg' %}" alt="back to list" id="back-arrow">
</a>
<div class="page-content">
  <div class="header">
    <h1>{{ movie.movie_title }}</h1>
    {% if movie.watch_state == "WD" %}
      <p>{{ movie.rating }}</p>
    {% endif %}
  </div>
  <div>
  <p class="movie-summary">{{ movie.synopsis }}</p>
  <h2><a href="/watchlist/{{movie.id}}/movie-cast">CAST LIST</a></h2>

  <form action="{% url 'watchlist:movie_detail' movie.id %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="update">
  </form>

</div>

watchlist/templates/watchlist/movie_index.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'css/movie_index.css' %}">
</head>

<script>
function toggleWatchlistMenu() {
  var hid_lists = document.getElementsByClassName("hidden-list");
  var shown_lists = document.getElementsByClassName("not-hidden-list");

  if (hid_lists.length > 0) {
    console.log(hid_lists.length)
    for (i = 0; 0 < hid_lists.length; i++) {
      console.log(hid_lists)
      hid_lists[0].setAttribute("class", "not-hidden-list");
    }
  } else {
    for (i = 0; 0 < shown_lists.length; i++) {
      shown_lists[0].setAttribute("class", "hidden-list");
    }
  }
}

function sortByRating() {
  var button = document.getElementById("by-rating");
  var otherButton = document.getElementById("by-date");
  var rlist = document.getElementById("ranked-list");
  var clist = document.getElementById("chronological-list");

  rlist.style.display = "flex";
  clist.style.display = "none";
  button.style.fontWeight = "bold";
  otherButton.style.fontWeight = "normal";
}

function sortByDate() {
  var button = document.getElementById("by-date");
  var otherButton = document.getElementById("by-rating");
  var rlist = document.getElementById("ranked-list");
  var clist = document.getElementById("chronological-list");

  clist.style.display = "flex";
  rlist.style.display = "none";
  button.style.fontWeight = "bold";
  otherButton.style.fontWeight = "normal";
}

function toggleShowMenu() {
  var menuEls = document.getElementsByClassName("list-type-menu");

  if (menuEls[0].style.display !== "flex") {
    for (i = 0; i < menuEls.length; i++) {
      menuEls[i].style.display = "flex";
    }
  } else {
    for (i = 0; i < menuEls.length; i++) {
      menuEls[i].style.display = "none";
    }
  }
}


function searchMovies() {
  var search_prompt = document.getElementById("movie-search").value;
  var search_prompt = document.getElementById("movie-search").value;
  var list_name = document.getElementById("current-list").textContent;
  console.log(list_name.substr(0,list_name.length-2));
  location.href="/watchlist/movie-options/" + list_name.substr(0,list_name.length-2) + "/" + search_prompt
}


function collapseList(list_class, icon_id) {
  var list_elements = document.getElementsByClassName(list_class);
  var icon = document.getElementById(icon_id);

  if (list_elements[0].style.display === "none") {
    for (i = 0; i < list_elements.length; i++) {
      list_elements[i].style.display = "flex";
      icon.style.transform = "rotate(0deg)";
    }
  } else {
    for (i = 0; i < list_elements.length; i++) {
      list_elements[i].style.display = "none";
      icon.style.transform = "rotate(180deg)";
    }
  }
}


</script>

<div id="page-decoration"  style="background-color:{{watchlst.color}}"></div>
<div id="sort-by">Sort by &nbsp; <div id="by-rating" onclick="sortByRating()">Rating</div> &nbsp; | &nbsp; <div id="by-date" onclick="sortByDate()">Date</div></div>
<div class="page-content">

  <div class="movie-preview" style="display:block; filter: drop-shadow(-2px 5px 13px black)"></div>

  <div id="watched-movie-list">
    <div class="list-header">
      <div class="list-menu">
        {% for list in lists %}
          <a class="hidden-list" href="/watchlist/{{list.name}}/movies"><h1>{{list.name}}</h1></a>
        {% endfor %}
        <span id="current-list" style="color:{{watchlst.color}}" onclick="toggleWatchlistMenu()"><h1>{{watchlst.name}}'s</h1></span>
      </div>
      <div id="title-type-header">
        <a class="list-type-menu" href="/watchlist/{{watchlst.name}}/shows"><h1>Shows</h1></a>
        <a class="list-type-menu" href="/watchlist/{{watchlst.name}}/actors"><h1>Actors</h1></a>
        <div style="display: flex">
          <h1 id="movies-menu" onclick="toggleShowMenu()">Movies </h1>
          <img src="{% static 'images/collapse_arrow.png' %}" alt="collapse" id="watched-collapse-icon" style="height: 25px; align-self: center" onclick="collapseList('watched-movie', 'watched-collapse-icon')">
        </div>
      </div>
    </div>

    <div id="watching-list">
      {% if ranked_list %}
        <div id="ranked-list">
          <ul>
          {% for movie in ranked_list %}
              <div class="watched-movie"><a href="{% url 'watchlist:movie_detail' movie.id %}">{{ movie.movie_title }}</a></div>
              <div class="movie-preview">
                <img class="preview-img" src="{{movie.featured_img}}">
                <div class="preview-right-col">
                    <h1>{{ movie.movie_title }}</h1>
                    <h1 class="rating" style="color:{{watchlst.color}}">{{ movie.rating }}</h1>
                    <p>{{ movie.synopsis }}</p>
                </div>
             </div>
          {% endfor %}
          </ul>
        </div>

        <div id="chronological-list">
          <ul>
          {% for movie in chronological_list %}
              <div class="watched-movie"><a href="{% url 'watchlist:movie_detail' movie.id %}">{{ movie.movie_title }}</a></div>
              <div class="movie-preview">
                <img class="preview-img" src="{{movie.featured_img}}">
                <div class="preview-right-col">
                    <h1>{{ movie.movie_title }}</h1>
                    <h1 class="rating" style="color:{{watchlst.color}}">{{ movie.rating }}</h1>
                    <p>{{ movie.synopsis }}</p>
                </div>
             </div>
          {% endfor %}
          </ul>
        </div>
      {% else %}
          <p >You haven't watched any movies I guess. </p>
      {% endif %}
    </div>
  </div>

  <div id="to-watch-list">
    {% if to_watch_list %}
        <h1> To Watch: </h1>
        <ul>
          <div id="queued-items">
          {% for movie in to_watch_queued %}
              <div class="movie-to-watch">
                <a href="{% url 'watchlist:movie_detail' movie.id %}">{{ movie.movie_title }}</a>
              </div>
              <div class="movie-preview queued-preview" style="outline-color:{{watchlst.color}};">
                  <img class="preview-img" src="{{movie.featured_img}}">
                  <div class="preview-right-col">
                      <h1>{{ movie.movie_title }}</h1>
                      <p>{{ movie.synopsis }}</p>
                  </div>
             </div>
          {% endfor %}
          </div>

          {% for movie in to_watch_list %}
            <div class="movie-to-watch">
              <a href="{% url 'watchlist:movie_detail' movie.id %}">{{ movie.movie_title }}</a>
            </div>
            <div class="movie-preview">
                <img class="preview-img" src="{{movie.featured_img}}">
                <div class="preview-right-col">
                    <h1>{{ movie.movie_title }}</h1>
                    <p>{{ movie.synopsis }}</p>
                </div>
           </div>
        {% endfor %}
        </ul>
    {% endif %}

    <input type="text" name="movie-search" id="movie-search" placeholder="add a new movie" value="">
    <button type="button" name="button" onclick="searchMovies()">find movie</button>

  </div>
</div>

watchlist/templates/watchlist/newmovie.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/newmovie.css' %}">
</head>

<form action="{% url 'watchlist:new_movie' watchlst.name%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

watchlist/templates/watchlist/newmovieoptions.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/newmovie.css' %}">
</head>
<form action="{% url 'watchlist:new_movie_options' watchlst.name search_text%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

watchlist/templates/watchlist/newshowoptions.html
{% load static %}
<head>
    <link rel="stylesheet" href="{% static 'css/newmovie.css' %}">
</head>
<form action="{% url 'watchlist:new_show_options' watchlst.name search_text%}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>

watchlist/templates/watchlist/show-detail.html
{% load static %}
<head>
  <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<a href="/watchlist/{{show.list.name}}/shows">
  <img src="{% static 'images/arrow.svg' %}" alt="back to list" id="back-arrow">
</a>
<div class="page-content">
  <div class="header">
    <h1>{{ show.show_title }}</h1>
    {% if show.watch_state == "WD" %}
      <p>{{ movie.rating }}</p>
    {% endif %}
  </div>
  <div>
  <p class="movie-summary">{{ show.synopsis }}</p>
  <h2><a href="/watchlist/{{show.id}}/show-cast">CAST LIST</a></h2>

  <form action="{% url 'watchlist:show_detail' show.id %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="update">
  </form>

</div>